[[constraint]]
  name = "github.com/nuvo/skbn"
  version = "0.4.2"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  branch = "release-1.13"
  name = "k8s.io/apimachinery"

[prune]
  go-tests = true
  unused-packages = true
